### PR TITLE
reconstruct specified atoms only

### PR DESCRIPTION
**Pull request by tnamoradze**
NB! Currently there is no way to reconstruct any of parity shards without reconstructing all data shards first. at least without brain surgery. So if parity shard is ordered then all data shards will be reconstructed anyway. This is still better then reconstructing all parity atoms.

---
This change is [Reviewable](https://reviewable.io/reviews/istreamdata/reedsolomon/1)

### CODE REVIEW

**Comment by dennwc** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[reedsolomon.go, line 63 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks5oKoH6dmVrNqzd5QQ:-Ks5oKoH6dmVrNqzd5QR:b-v85f8o) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L63)):*
> ```Go
> 	// Behavior is similar to Reconstruct, but it will rebuild only atoms at idxs
> 	// and also all data atoms if any of the requested index is a parity shard index.
> 	ReconstructAtoms(shards [][]byte, idxs ...int) error
> ```

It can be the same method as ReconstructData. If indexes are not specified, it reconstructs only base, and if they are, then we reconstruct only selected indexes.

On second thought it might be even better to make original Reconstruct behave this way. We can remove ReconstructData in this case.

---

*[reedsolomon.go, line 419 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks8MgOO7sOrG4REhufB:-Ks8MgOO7sOrG4REhufC:b4g146i) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L419)):*
> ```Go
> 	for i := 0; i < r.Shards; i++ {
> 		if len(shards[i]) != 0 {
> 			if len(idxs) > 0 && contains(idxs, i) {
> ```

This looks wrong. `idxs` may contain parity shards, right? Why it increments `dataPresent` then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 63 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks5oKoH6dmVrNqzd5QQ:-KsDnDzK14Ha-nZv4efE:b-5r845n) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L63)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

It can be the same method as ReconstructData. If indexes are not specified, it reconstructs only base, and if they are, then we reconstruct only selected indexes.

On second thought it might be even better to make original Reconstruct behave this way. We can remove ReconstructData in this case.
</blockquote></details>

not sure. for me this looks more clear. ReconstructData reconstructs only all data, pretty awesome and clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 419 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks8MgOO7sOrG4REhufB:-KsDmJmI38XvFif-9AGa:b-8xw0lu) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L419)):*
> dataPresent
represents counter not for base blocks that are present, but instead counter of blocks that we request via indexes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by dennwc** [comment]
Looks good overall, but few questions about naming

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[reedsolomon.go, line 63 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks5oKoH6dmVrNqzd5QQ:-KsONueEDmH0sNcrZ-Wm:b-ke1bqr) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L63)):*
<details><summary><i>Previously, tnamoradze (Temo) wrote…</i></summary><blockquote>

not sure. for me this looks more clear. ReconstructData reconstructs only all data, pretty awesome and clear.
</blockquote></details>

But this makes an interface even larger. It's better to keep interfaces short and clean.

---

*[reedsolomon.go, line 365 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOLAsQUX2_6Uf3Ekag:-KsOLAsQUX2_6Uf3Ekah:b4yymaa) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L365)):*
> ```Go
> // Use the Verify function to check if data set is ok.
> func (r reedSolomon) Reconstruct(shards [][]byte) error {
> 	return r.reconstructP(shards, true)
> ```

Let's just call `r.reconstruct` here directly

---

*[reedsolomon.go, line 379 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOLHm1HqwU6gpy_j8t:-KsOLHm1HqwU6gpy_j8u:bawybxg) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L379)):*
> ```Go
> // Behavior is similar to Reconstruct, but it will rebuild only atoms at idxs
> // and also all data atoms if any of the requested index is a parity shard index.
> func (r reedSolomon) ReconstructAtoms(shards [][]byte, idxs ...int) error {
> ```

"atoms" is a term from Datomia, while this library calls them "shards", so let's rename it accordingly (ReconstructShards)

---

*[reedsolomon.go, line 383 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOLRYgJyn8iqD_q7xD:-KsOLRYgJyn8iqD_q7xE:b85rlnq) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L383)):*
> ```Go
> }
> 
> func (r reedSolomon) reconstructP(shards [][]byte, parity bool) error {
> ```

This can be inlined to ReconstructAtoms (and parity flag can be dropped)

---

*[reedsolomon.go, line 419 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks8MgOO7sOrG4REhufB:-KsOLig2YWM_ahwvANCq:bjjzsv2) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L419)):*
<details><summary><i>Previously, tnamoradze (Temo) wrote…</i></summary><blockquote>

> dataPresent
represents counter not for base blocks that are present, but instead counter of blocks that we request via indexes.
</blockquote></details>

It should be named accordingly, then. Maybe `requiredPresent`?

---

*[reedsolomon.go, line 454 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOMJjoJCgtoOrrtvXO:-KsOMJjoJCgtoOrrtvXP:bmd5fi3) ([raw file](https://github.com/istreamdata/reedsolomon/blob/32c83a8dbd1e3e04e1612c8dc4f1483e12d74a99/reedsolomon.go#L454)):*
> ```Go
> 	r.codeSomeShards(matrixRows, subShards, outputs[:outputCount], outputCount, shardSize)
> 
> 	if !parity {
> ```

Why this was removed? If we specifiy all data shards, then we can stop here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-:-KsONTBR37I4N-KktX4Q:b-9or464)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 365 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOLAsQUX2_6Uf3Ekag:-KsrsvrrGbGJFugrW9zq:b-896fix) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L365)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Let's just call `r.reconstruct` here directly
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 379 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOLHm1HqwU6gpy_j8t:-Ksrt8_jVSsCbN8aDGbP:b-896fix) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L379)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

"atoms" is a term from Datomia, while this library calls them "shards", so let's rename it accordingly (ReconstructShards)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 383 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOLRYgJyn8iqD_q7xD:-KsrtGuywHZhyRa6gsj9:b-896fix) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L383)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

This can be inlined to ReconstructAtoms (and parity flag can be dropped)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 419 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-Ks8MgOO7sOrG4REhufB:-KsrtVEiwMVpWdSFn78e:b-896fix) ([raw file](https://github.com/istreamdata/reedsolomon/blob/c497372b63dae5cec37b8fba7ace359838b8dcaa/reedsolomon.go#L419)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

It should be named accordingly, then. Maybe `requiredPresent`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by tnamoradze** [comment]
*[reedsolomon.go, line 454 at r1](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-KsOMJjoJCgtoOrrtvXO:-KsrubY5AVqWX0LqWSAQ:b-77a678) ([raw file](https://github.com/istreamdata/reedsolomon/blob/32c83a8dbd1e3e04e1612c8dc4f1483e12d74a99/reedsolomon.go#L454)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Why this was removed? If we specifiy all data shards, then we can stop here.
</blockquote></details>

This code below controls which parity shards have to be reconstructed, if none of the parity shard index is requested then  codeSomeShards will not reconstruct any. 

if len(idxs) > 0 && !contains(idxs, iShard) {
				continue
			}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1)*

**Comment by dennwc** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istreamdata/reedsolomon/1#-:-KsrxIRF9RvWZ6THv2Pk:bnfp4nl)*

**Pull request merged**
